services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs1
      - nodejs2
    networks:
      - app_network

  nodejs1:
    image: node:22
    container_name: nodejs1
    working_dir: /app
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    command: npm start
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  nodejs2:
    image: node:22
    container_name: nodejs2
    working_dir: /app
    volumes:
      - ./app:/app
      - ./.env:/app/.env
    command: npm start
    environment:
      - NODE_ENV=production
    networks:
      - app_network

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
